/* ══════════════════════════════════════
   PRODUCTS CATALOGUE
══════════════════════════════════════ */
const products = [
  // ========== ДЕТСКОЕ ПИТАНИЕ ==========
  { 
    id: 1, 
    brand_uz: 'Hero Baby',
    brand_ru: 'Hero Baby',
    name_uz: 'Hero Baby bolalar kashasi Banan mazali', 
    name_ru: 'Hero Baby детская каша со вкусом банана', 
    cat_uz: 'bolalar uchun', 
    cat_ru: 'для детей', 
    price: 21000, 
    unit_uz: 'dona', 
    unit_ru: 'шт', 
    emoji: '🍌', 
    img: 'photos/herobabybanan.jpg',
    desc_uz: 'Bolalar uchun banan mazali quruq kasha. Tarkibida vitaminlar (A, C, D, E) va minerallar (temir, kaltsiy) mavjud. Tabiiy banan pyuresi bilan boyitilgan. 6 oydan boshlab foydalanish tavsiya etiladi.',
    desc_ru: 'Детская сухая каша со вкусом банана. Содержит витамины (A, C, D, E) и минералы (железо, кальций). Обогащена натуральным банановым пюре. Рекомендуется с 6 месяцев.',
    promo: '1+1',
    promo_desc_uz: 'Aksiya: 1+1 – ikkinchi mahsulot sovgʻa sifatida beriladi! Yetarli miqdorda sotib oling va omboringizni toʻldiring. Tafsilotlar uchun agentingizga murojaat qiling.',
    promo_desc_ru: 'Акция: 1+1 – второй товар в подарок! Закупайтесь впрок и пополняйте склад. Подробности у вашего агента.'
  },
  { 
    id: 2, 
    brand_uz: 'Hero Baby',
    brand_ru: 'Hero Baby',
    name_uz: 'Hero Baby bolalar kashasi oddiy', 
    name_ru: 'Hero Baby детская каша обычная', 
    cat_uz: 'bolalar uchun', 
    cat_ru: 'для детей', 
    price: 21000, 
    unit_uz: 'dona', 
    unit_ru: 'шт', 
    emoji: '🍚', 
    img: 'photos/herobabyguruch.jpg',
    desc_uz: 'Klassik guruchli quruq kasha. Tarkibida probiotiklar va prebiyotiklar mavjud. Oshqozon-ichak traktini yaxshilaydi. 4 oydan boshlab foydalanish mumkin.',
    desc_ru: 'Классическая сухая рисовая каша. Содержит пробиотики и пребиотики. Улучшает пищеварение. Можно использовать с 4 месяцев.',
    promo: '1+1',
    promo_desc_uz: 'Aksiya: 1+1 – ikkinchi mahsulot sovgʻa sifatida beriladi! Yetarli miqdorda sotib oling va omboringizni toʻldiring. Tafsilotlar uchun agentingizga murojaat qiling.',
    promo_desc_ru: 'Акция: 1+1 – второй товар в подарок! Закупайтесь впрок и пополняйте склад. Подробности у вашего агента.'
  },
  { 
    id: 3, 
    brand_uz: 'Hero Baby',
    brand_ru: 'Hero Baby',
    name_uz: 'Hero Baby bolalar kashasi olma va nok mazali', 
    name_ru: 'Hero Baby детская каша со вкусом яблок и груши', 
    cat_uz: 'bolalar uchun', 
    cat_ru: 'для детей', 
    price: 21000, 
    unit_uz: 'dona', 
    unit_ru: 'шт', 
    emoji: '🍎🍐', 
    img: 'photos/herobabymeva.jpg',
    desc_uz: 'Olma va nok pyuresi qo‘shilgan quruq kasha. Tabiiy meva ta’mi, vitaminlar va tolalar bilan boyitilgan. Immunitetni mustahkamlaydi. 6 oydan boshlab tavsiya etiladi.',
    desc_ru: 'Сухая каша с добавлением яблочного и грушевого пюре. Натуральный фруктовый вкус, обогащена витаминами и клетчаткой. Укрепляет иммунитет. Рекомендуется с 6 месяцев.',
    promo: '1+1',
    promo_desc_uz: 'Aksiya: 1+1 – ikkinchi mahsulot sovgʻa sifatida beriladi! Yetarli miqdorda sotib oling va omboringizni toʻldiring. Tafsilotlar uchun agentingizga murojaat qiling.',
    promo_desc_ru: 'Акция: 1+1 – второй товар в подарок! Закупайтесь впрок и пополняйте склад. Подробности у вашего агента.'
  },
  { 
    id: 4, 
    brand_uz: 'Hero Baby',
    brand_ru: 'Hero Baby',
    name_uz: 'Hero Baby bolalar kashasi olma mazali', 
    name_ru: 'Hero Baby детская каша со вкусом яблок', 
    cat_uz: 'bolalar uchun', 
    cat_ru: 'для детей', 
    price: 21000, 
    unit_uz: 'dona', 
    unit_ru: 'шт', 
    emoji: '🍎', 
    img: 'photos/herobabyolma.jpg',
    desc_uz: 'Olma pyuresi qo‘shilgan quruq kasha. Tarkibida temir va vitamin C ko‘p. Bolaning o‘sishi va rivojlanishiga yordam beradi. 6 oydan boshlab foydalanish mumkin.',
    desc_ru: 'Сухая каша с добавлением яблочного пюре. Богата железом и витамином C. Способствует росту и развитию ребёнка. Можно использовать с 6 месяцев.',
    promo: '1+1',
    promo_desc_uz: 'Aksiya: 1+1 – ikkinchi mahsulot sovgʻa sifatida beriladi! Yetarli miqdorda sotib oling va omboringizni toʻldiring. Tafsilotlar uchun agentingizga murojaat qiling.',
    promo_desc_ru: 'Акция: 1+1 – второй товар в подарок! Закупайтесь впрок и пополняйте склад. Подробности у вашего агента.'
  },
  { 
    id: 5, 
    brand_uz: 'Hero Baby',
    brand_ru: 'Hero Baby',
    name_uz: 'Hero Baby bolalar kashasi qulupnay va malina mazali', 
    name_ru: 'Hero Baby детская каша со вкусом клубники и малины', 
    cat_uz: 'bolalar uchun', 
    cat_ru: 'для детей', 
    price: 21000, 
    unit_uz: 'dona', 
    unit_ru: 'шт', 
    emoji: '🍓', 
    img: 'photos/herobabyqulupnay.jpg',
    desc_uz: 'Qulupnay va malina pyuresi qo‘shilgan quruq kasha. Tabiiy rezavor ta’m, antioksidantlar va vitaminlar bilan boyitilgan. Bolaning immunitetini mustahkamlaydi. 8 oydan boshlab tavsiya etiladi.',
    desc_ru: 'Сухая каша с добавлением пюре клубники и малины. Натуральный ягодный вкус, обогащена антиоксидантами и витаминами. Укрепляет иммунитет ребёнка. Рекомендуется с 8 месяцев.',
    promo: '1+1',
    promo_desc_uz: 'Aksiya: 1+1 – ikkinchi mahsulot sovgʻa sifatida beriladi! Yetarli miqdorda sotib oling va omboringizni toʻldiring. Tafsilotlar uchun agentingizga murojaat qiling.',
    promo_desc_ru: 'Акция: 1+1 – второй товар в подарок! Закупайтесь впрок и пополняйте склад. Подробности у вашего агента.'
  },
    // ========== ЗЛАКОВЫЕ ЗАВТРАКИ HAY BAFFY ==========
  {
    id: 999,
    brand_uz: 'Hay Baffy',
    brand_ru: 'Hay Baffy',
    name_uz: 'Hay Baffy Duo shar 200g',
    name_ru: 'Hay Baffy Duo balls 200г',
    cat_uz: 'donli nonushta',
    cat_ru: 'злаковые завтраки',
    price: 13800,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🥣',
    img: 'photos/hay baffy duo mix 200gr.jpg',
    desc_uz: 'Hay Baffy Duo shar – butun donli zlaklardan tayyorlangan mazali va foydali nonushta. Tarkibida 100% bio ingredientlar, sun\'iy bo\'yoqlar va konservantlar yo\'q. Tolali moddalarga boy, ovqat hazm qilishni yaxshilaydi. 10 ta muhim vitamin va minerallar bilan boyitilgan. Tez va oson tayyorlanadi – sut yoki yogurt bilan iste\'mol qilish tavsiya etiladi. 200 grammli qulay paketda.',
    desc_ru: 'Hay Baffy Duo balls – вкусный и полезный завтрак из цельных злаков. Содержит 100% био-ингредиенты, без искусственных красителей и консервантов. Богат клетчаткой, улучшает пищеварение. Обогащён 10 важными витаминами и минералами. Быстро и легко готовится – рекомендуется употреблять с молоком или йогуртом. В удобной упаковке 200 г.',
    promo: 'Bonus',
  promo_desc_uz: '',
    promo_desc_ru: '' },
  {
    id: 998,
    brand_uz: 'Hay Baffy',
    brand_ru: 'Hay Baffy',
    name_uz: 'Hay Baffy Shokoladli shar 200g',
    name_ru: 'Hay Baffy Chocolate balls 200г',
    cat_uz: 'donli nonushta',
    cat_ru: 'злаковые завтраки',
    price: 13800,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍫',
    img: 'photos/hay baffy chocolate 200gr.jpeg',
    desc_uz: 'Hay Baffy Shokoladli shar – shokolad ta’mli butun donli zlaklar. Tarkibida sun\'iy konservantlar yo\'q, tabiiy shokolad aromati bilan. Tolali moddalar va 10 ta vitamin (A, C, D, E, B guruhi) bilan boyitilgan. Energetik va to\'yimli nonushta, kunni quvnoq boshlashga yordam beradi. Sut yoki yogurt bilan berilsa, bolalar juda yoqtiradi. 200 grammli qulay paket.',
    desc_ru: 'Hay Baffy Chocolate balls – цельнозлаковые шарики со вкусом шоколада. Без искусственных консервантов, с натуральным шоколадным ароматом. Обогащены клетчаткой и 10 витаминами (A, C, D, E, группы B). Энергичный и сытный завтрак, помогает бодро начать день. Детям очень нравится с молоком или йогуртом. В удобной упаковке 200 г.',
    promo: 'Bonus',
  promo_desc_uz: '',
    promo_desc_ru: '' },
  {
    id: 505,
    brand_uz: 'Hay Baffy',
    brand_ru: 'Hay Baffy',
    name_uz: 'Hay Baffy Shokoladli shar 375g',
    name_ru: 'Hay Baffy Chocolate balls 375г',
    cat_uz: 'donli nonushta',
    cat_ru: 'злаковые завтраки',
    price: 28500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍫',
    img: 'photos/hay baffy chocolate 375gr.jpg',
    desc_uz: 'Hay Baffy Shokoladli shar – shokolad ta’mli butun donli zlaklar. Tarkibida sun\'iy konservantlar yo\'q, tabiiy shokolad aromati bilan. Tolali moddalar va 10 ta vitamin (A, C, D, E, B guruhi) bilan boyitilgan. Energetik va to\'yimli nonushta, kunni quvnoq boshlashga yordam beradi. Sut yoki yogurt bilan berilsa, bolalar juda yoqtiradi. 375 grammli paket.',
    desc_ru: 'Hay Baffy Chocolate balls – цельнозлаковые шарики со вкусом шоколада. Без искусственных консервантов, с натуральным шоколадным ароматом. Обогащены клетчаткой и 10 витаминами (A, C, D, E, группы B). Энергичный и сытный завтрак, помогает бодро начать день. Детям очень нравится с молоком или йогуртом. Упаковка 375 г.',
    promo: 'Bonus',
  promo_desc_uz: '',
    promo_desc_ru: ''},
  {
    id: 997,
    brand_uz: 'Hay Baffy',
    brand_ru: 'Hay Baffy',
    name_uz: 'Hay Baffy Duo shar 450g',
    name_ru: 'Hay Baffy Duo balls 450г',
    cat_uz: 'donli nonushta',
    cat_ru: 'злаковые завтраки',
    price: 28500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🥣',
    img: 'photos/hay baffy 450gr.jpeg',
    desc_uz: 'Hay Baffy Duo shar – butun donli zlaklardan tayyorlangan mazali va foydali nonushta. Tarkibida 100% bio ingredientlar, sun\'iy bo\'yoqlar va konservantlar yo\'q. Tolali moddalarga boy, ovqat hazm qilishni yaxshilaydi. 10 ta muhim vitamin va minerallar bilan boyitilgan. Tez va oson tayyorlanadi – sut yoki yogurt bilan iste\'mol qilish tavsiya etiladi. 450 grammli katta paket – butun oila uchun yetarli.',
    desc_ru: 'Hay Baffy Duo balls – вкусный и полезный завтрак из цельных злаков. Содержит 100% био-ингредиенты, без искусственных красителей и консервантов. Богат клетчаткой, улучшает пищеварение. Обогащён 10 важными витаминами и минералами. Быстро и легко готовится – рекомендуется употреблять с молоком или йогуртом. В большой упаковке 450 г – достаточно для всей семьи.',
    promo: 'Bonus',
    promo_desc_uz: '',
    promo_desc_ru: ''  },
  {
    id: 996,
    brand_uz: 'Hay Baffy',
    brand_ru: 'Hay Baffy',
    name_uz: 'Hay Baffy Shokoladli shar 450g',
    name_ru: 'Hay Baffy Chocolate balls 450г',
    cat_uz: 'donli nonushta',
    cat_ru: 'злаковые завтраки',
    price: 28500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍫',
    img: 'photos/hay baffy chocolate 450gr.jpg',
    desc_uz: 'Hay Baffy Shokoladli shar – shokolad ta’mli butun donli zlaklar. Tarkibida sun\'iy konservantlar yo\'q, tabiiy shokolad aromati bilan. Tolali moddalar va 10 ta vitamin (A, C, D, E, B guruhi) bilan boyitilgan. Energetik va to\'yimli nonushta, kunni quvnoq boshlashga yordam beradi. 450 grammli katta paket – katta oila uchun ideal, bir necha kun yetadi.',
    desc_ru: 'Hay Baffy Chocolate balls – цельнозлаковые шарики со вкусом шоколада. Без искусственных консервантов, с натуральным шоколадным ароматом. Обогащены клетчаткой и 10 витаминами (A, C, D, E, группы B). Энергичный и сытный завтрак, помогает бодро начать день. В большой упаковке 450 г – идеально для большой семьи, хватает на несколько дней.',
    promo: 'Bonus',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 707,
    brand_uz: 'Hay Baffy',
    brand_ru: 'Hay Baffy',
    name_uz: 'Hay Baffy Shokoladli shar 4kg',
    name_ru: 'Hay Baffy Chocolate balls 4кг',
    cat_uz: 'donli nonushta',
    cat_ru: 'злаковые завтраки',
    price: 156000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍫',
    img: 'photos/hay baffy 4kg.jpg',
    desc_uz: 'Hay Baffy Shokoladli shar – shokolad ta’mli butun donli zlaklardan iborat katta hajmli (4 kg) paket. Tarkibida sun\'iy konservantlar yo\'q, tabiiy shokolad aromati bilan. Tolali moddalar va 10 ta vitamin bilan boyitilgan. Kafe, maktab oshxonalari va katta oilalar uchun ideal. Iqtisodiy va qulay.',
    desc_ru: 'Hay Baffy Chocolate balls – цельнозлаковые шарики со вкусом шоколада в большой упаковке (4 кг). Без искусственных консервантов, с натуральным шоколадным ароматом. Обогащены клетчаткой и 10 витаминами. Идеально для кафе, школьных столовых и больших семей. Экономично и удобно.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 614,
    brand_uz: 'Hay Baffy',
    brand_ru: 'Hay Baffy',
    name_uz: 'Hay Baffy Duo shar 4kg',
    name_ru: 'Hay Baffy Duo balls 4кг',
    cat_uz: 'donli nonushta',
    cat_ru: 'злаковые завтраки',
    price: 156000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🥣',
    img: 'photos/hay baffy 4kg.jpg',
    desc_uz: 'Hay Baffy Duo shar – butun donli zlaklardan tayyorlangan, 100% bio ingredientli katta hajmli (4 kg) paket. Sun\'iy bo\'yoqlar va konservantlar yo\'q. Tolali moddalarga boy, 10 ta vitamin va minerallar bilan boyitilgan. Kafe, maktab va katta oilalar uchun qulay.',
    desc_ru: 'Hay Baffy Duo balls – из цельных злаков, 100% био-ингредиенты, большая упаковка (4 кг). Без искусственных красителей и консервантов. Богат клетчаткой, обогащён 10 витаминами и минералами. Удобно для кафе, школ и больших семей.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  // ========== СРЕДСТВА ДЛЯ МЫТЬЯ ПОСУДЫ AS ==========
  {
    id: 6,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli 200gr',
    name_ru: 'AS гель для мытья посуды 200гр',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 5100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧼',
    img: 'photos/as200grgel.jpg',
    desc_uz: 'AS idish yuvish geli – yog‘ va iflosliklarni samarali tozalaydi. Konsentrlangan formula, 200 gramm hajmda. Qo‘llarni yumshoq tozalaydi, terini tirnashmaydi. Idishlarni porloq qilib yuvadi, suvda oson chayiladi. Iqtisodiy sarflanadi – bir tomchi gel ko‘p ko‘pik hosil qiladi.',
    desc_ru: 'Гель для мытья посуды AS – эффективно удаляет жир и загрязнения. Концентрированная формула, объём 200 грамм. Бережно очищает руки, не раздражает кожу. Придаёт посуде блеск, легко смывается водой. Экономичен – одна капля геля даёт обильную пену.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 17,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli ULTRACARE 400g',
    name_ru: 'AS гель для мытья посуды ULTRACARE 400г',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 9950,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧼',
    img: 'photos/asgel400gr.jpg',
    desc_uz: 'AS ULTRACARE idish yuvish geli – 400 grammli qulay paket. Yog‘ va dog‘larni samarali tozalaydi. Qo‘llarni yumshoq tozalaydi, terini himoya qiladi. Idishlarni porloq qiladi, suvda oson chayiladi. Kichik oila uchun ideal.',
    desc_ru: 'AS ULTRACARE гель для мытья посуды – удобная упаковка 400 г. Эффективно удаляет жир и пятна. Бережно очищает руки, защищает кожу. Придаёт посуде блеск, легко смывается. Идеален для небольшой семьи.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  // НОВЫЕ 750г
  {
    id: 25,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli "Kaplya" apelsin 750g',
    name_ru: 'AS гель для мытья посуды "Капля" апельсин 750г',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 7300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍊',
    img: 'photos/asgelkaplyaapelsin.jpg',
    desc_uz: 'AS "Kaplya" idish yuvish geli – apelsin aromati bilan. 750 grammli iqtisodiy paket. Yog‘ va iflosliklarni samarali tozalaydi, ko‘pik hosil qiladi. Idishlarni porloq qiladi, suvda oson chayiladi. O‘rtacha oila uchun qulay hajm.',
    desc_ru: 'AS "Капля" гель для мытья посуды – с ароматом апельсина. Экономичная упаковка 750 г. Эффективно удаляет жир и загрязнения, пенится. Придаёт посуде блеск, легко смывается. Удобный объём для средней семьи.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 26,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli "Kaplya" olma 750g',
    name_ru: 'AS гель для мытья посуды "Капля" яблоко 750г',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 7300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍎',
    img: 'photos/asgelkaplyaolma.jpg',
    desc_uz: 'AS "Kaplya" idish yuvish geli – olma aromati bilan. 750 grammli qulay paket. Yog‘ va dog‘larni samarali tozalaydi. Idishlarni porloq qiladi, suvda oson chayiladi. Kundalik foydalanish uchun ideal.',
    desc_ru: 'AS "Капля" гель для мытья посуды – с ароматом яблока. Удобная упаковка 750 г. Эффективно удаляет жир и пятна. Придаёт посуде блеск, легко смывается. Идеален для ежедневного использования.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 27,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli "Kaplya" ko‘k 750g',
    name_ru: 'AS гель для мытья посуды "Капля" голубой 750г',
   cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 7300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '💧',
    img: 'photos/asgelkaplyako\'k.jpg',
    desc_uz: 'AS "Kaplya" idish yuvish geli – dengiz tetiklashtiruvchi aromati bilan. 750 grammli paket. Yog‘ va iflosliklarni samarali tozalaydi, idishlarni porloq qiladi. Suvda oson chayiladi, iqtisodiy sarflanadi.',
    desc_ru: 'AS "Капля" гель для мытья посуды – с освежающим морским ароматом. Упаковка 750 г. Эффективно удаляет жир и загрязнения, придаёт посуде блеск. Легко смывается, экономичен.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 18,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli limon 900g',
    name_ru: 'AS гель для мытья посуды лимон 900г',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 20500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍋',
    img: 'photos/asgel900gr.jpg',
    desc_uz: 'AS idish yuvish geli – limon aromati bilan, 900 gramm hajmda. Yog‘ va iflosliklarni tez tozalaydi, ko‘p ko‘pik hosil qiladi. Idishlarni porloq qiladi, suvda oson chayiladi. O‘rtacha oila uchun qulay hajm.',
    desc_ru: 'AS гель для мытья посуды – с ароматом лимона, объём 900 г. Быстро удаляет жир и загрязнения, даёт обильную пену. Придаёт посуде блеск, легко смывается. Удобный объём для средней семьи.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 14,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli ULTRACARE 1l',
    name_ru: 'AS гель для мытья посуды ULTRACARE 1л',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 22400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧼',
    img: 'photos/asgel1l.jpg',
    desc_uz: 'AS ULTRACARE idish yuvish geli – yog‘ va iflosliklarni samarali tozalaydi. Konsentrlangan formula, 1 litr hajmda. Qo‘llarni yumshoq tozalaydi, terini tirnashmaydi. Idishlarni porloq qiladi, suvda oson chayiladi.',
    desc_ru: 'AS ULTRACARE гель для мытья посуды – эффективно удаляет жир и загрязнения. Концентрированная формула, объём 1 л. Бережно очищает руки, не раздражает кожу. Придаёт посуде блеск, легко смывается водой.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 15,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli limon 5l',
    name_ru: 'AS гель для мытья посуды лимон 5л',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 28000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍋',
    img: 'photos/asgel5llimon.jpg',
    desc_uz: 'AS idish yuvish geli – limon aromati bilan. 5 litrlik katta iqtisodiy paket. Yog‘ va dog‘larni samarali tozalaydi, ko‘p ko‘pik hosil qiladi. Idishlarni porloq qiladi, suvda oson chayiladi. Kafe va restoranlar uchun ham mos.',
    desc_ru: 'AS гель для мытья посуды – с ароматом лимона. Большая экономичная упаковка 5 л. Эффективно удаляет жир и пятна, даёт обильную пену. Придаёт посуде блеск, легко смывается. Подходит для кафе и ресторанов.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 16,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli olma 5l',
    name_ru: 'AS гель для мытья посуды яблоко 5л',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 28000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍎',
    img: 'photos/asgel5lolma.jpg',
    desc_uz: 'AS idish yuvish geli – olma aromati bilan. 5 litrlik katta hajm. Yog‘ va iflosliklarni tezda tozalaydi, ko‘pik hosil qiladi. Idishlarni porloq va toza qiladi. Iqtisodiy sarf – bir necha oyga yetadi.',
    desc_ru: 'AS гель для мытья посуды – с ароматом яблока. Большой объём 5 л. Быстро удаляет жир и загрязнения, пенится. Делает посуду блестящей и чистой. Экономичный расход – хватает на несколько месяцев.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  // НОВЫЙ 5л олма (quyuqroq)
  {
    id: 28,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS idish yuvish geli olma (quyuq) 5l',
    name_ru: 'AS гель для мытья посуды яблоко (густой) 5л',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 35000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍎',
    img: 'photos/asgel5lolmaquyuqroq.jpg',
    desc_uz: 'AS idish yuvish geli – olma aromati bilan, quyuq formulali. 5 litrlik katta iqtisodiy paket. Yog‘ va dog‘larni samarali tozalaydi, ko‘pik hosil qiladi. Konsentrlangan formula – kam sarflanadi, uzoq vaqt yetadi.',
    desc_ru: 'AS гель для мытья посуды – с ароматом яблока, густая формула. Большая экономичная упаковка 5 л. Эффективно удаляет жир и пятна, пенится. Концентрированная формула – расходуется экономно, хватает надолго.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== СРЕДСТВА ДЛЯ МЫТЬЯ ПОСУДЫ PEGAS ==========
  {
    id: 29,
    brand_uz: 'Pegas',
    brand_ru: 'Pegas',
    name_uz: 'Pegas quyuq idish yuvish geli 1l',
    name_ru: 'Pegas густой гель для мытья посуды 1л',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 22000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧼',
    img: 'photos/pegas1lgel.jpg',
    desc_uz: 'Pegas quyuq idish yuvish geli – yog‘ va iflosliklarni samarali tozalaydi. Quyuq konsentrlangan formula – bir tomchi gel ko‘p ko‘pik hosil qiladi. 1 litr hajmda. Idishlarni porloq qiladi, suvda oson chayiladi. Iqtisodiy sarflanadi.',
    desc_ru: 'Pegas густой гель для мытья посуды – эффективно удаляет жир и загрязнения. Густая концентрированная формула – одна капля даёт обильную пену. Объём 1 л. Придаёт посуде блеск, легко смывается водой. Экономичен.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== СРЕДСТВА ДЛЯ СТИРКИ AS ==========
  {
    id: 9,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS universal kir yuvish geli 2.4l',
    name_ru: 'AS универсальный гель для стирки 2.4л',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 22000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧺',
    img: 'photos/asstirka2,4l.jpg',
    desc_uz: 'AS universal kir yuvish geli – barcha turdagi matolar uchun moʻljallangan. Har xil iflosliklarni samarali tozalaydi, matoga zarar yetkazmaydi. Konsentrlangan formula, 2.4 litr hajmda. Avtomat va qo‘lda yuvishga mos. Iqtisodiy sarflanadi – bir yuvish uchun 40–50 ml yetarli.',
    desc_ru: 'AS универсальный гель для стирки – подходит для всех типов тканей. Эффективно удаляет различные загрязнения, не повреждает ткань. Концентрированная формула, объём 2.4 л. Подходит для автоматической и ручной стирки. Экономичен – 40–50 мл на одну стирку.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 10,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS avtomat kir yuvish geli 3l (rangli va oq)',
    name_ru: 'AS гель для стирки автомат 3л (для цветного и белого)',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 50000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '👚',
    img: 'photos/Asstirka3l.jpg',
    desc_uz: 'AS avtomat kir yuvish geli – rangli va oq kiyimlar uchun universal. Matolarni ehtiyotkorona tozalaydi, dog‘larni samarali ketkazadi. Tarkibida matoni himoya qiluvchi komponentlar mavjud. 3 litr hajmda. Kundalik foydalanish uchun ideal. Yumshoq va yoqimli hid qoldiradi.',
    desc_ru: 'AS гель для стирки автомат – универсальный для цветного и белого белья. Бережно очищает ткани, эффективно удаляет пятна. Содержит компоненты, защищающие ткань. Объём 3 л. Идеален для ежедневного использования. Оставляет мягкий и приятный аромат.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 11,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS universal kir yuvish geli 5l',
    name_ru: 'AS универсальный гель для стирки 5л',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 35000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧺',
    img: 'photos/asstirka5l.jpg',
    desc_uz: 'AS universal kir yuvish geli – katta hajmli (5 litr) iqtisodiy paket. Barcha turdagi matolar uchun moʻljallangan, kuchli iflosliklarni tozalaydi. Avtomat va qo‘lda yuvish uchun mos. Katta oila yoki doimiy foydalanish uchun ideal tanlov.',
    desc_ru: 'AS универсальный гель для стирки – экономичная упаковка 5 литров. Подходит для всех типов тканей, удаляет стойкие загрязнения. Подходит для автоматической и ручной стирки. Идеальный выбор для большой семьи или частого использования.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== СРЕДСТВА ДЛЯ СТИРКИ PEGAS ==========
  {
    id: 7,
    brand_uz: 'Pegas',
    brand_ru: 'Pegas',
    name_uz: 'Pegas suyuq poroshok avtomat universal (har xil rang uchun)',
    name_ru: 'Pegas жидкий гель для стирки автомат универсальный (для цветного белья)',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 35000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '👕',
    img: 'photos/pegasqizilporoshok.jpg',
    desc_uz: 'Pegas Power Gel 3-in-1 – suyuq kir yuvish geli. Rangli kiyimlar uchun maxsus formula – ranglarni saqlaydi, oqarmaydi. 1950 ml hajmda. Kuchli iflosliklarni, ter va yog‘ dog‘larini samarali yuvadi. Antibakterial ta’sirga ega. Avtomat va qo‘lda yuvish uchun mos. Iqtisodiy sarflanadi – 1 yuvish uchun 30–40 ml yetarli.',
    desc_ru: 'Pegas Power Gel 3-in-1 – жидкий гель для стирки. Специальная формула для цветного белья – сохраняет яркость цветов, не выцветает. Объём 1950 мл. Эффективно удаляет стойкие загрязнения, пятна от крови и жира. Обладает антибактериальным действием. Подходит для автоматической и ручной стирки. Экономичен – 30–40 мл достаточно на одну стирку.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 8,
    brand_uz: 'Pegas',
    brand_ru: 'Pegas',
    name_uz: 'Pegas suyuq poroshok avtomat oq kiyimlar uchun',
    name_ru: 'Pegas жидкий гель для стирки автомат для белого белья',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 35000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🤍',
    img: 'photos/pegaskokporoshok.jpg',
    desc_uz: 'Pegas Power Gel 3-in-1 – oq kiyimlar uchun maxsus suyuq gel. Optik oqartiruvchilar va fermentlar bilan boyitilgan. Oqartirish va yangilash effekti – kiyimlarga porloq oqlikni qaytaradi. 1950 ml hajmda. Dog‘larni, sarg‘ayganlikni va kulranglikni ketkazadi. Avtomat va qo‘lda yuvishga mos. Iqtisodiy – 1 yuvish uchun 30–40 ml.',
    desc_ru: 'Pegas Power Gel 3-in-1 – специальный жидкий гель для белого белья. Обогащён оптическими отбеливателями и ферментами. Эффект отбеливания и обновления – возвращает белью ослепительную белизну. Объём 1950 мл. Удаляет пятна, желтизну и серый налёт. Подходит для автоматической и ручной стирки. Экономичный – 30–40 мл на одну стирку.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== ЧИСТЯЩИЕ СРЕДСТВА AS ==========
  {
    id: 12,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS antiyog‘ tozalovchi vosita 500ml',
    name_ru: 'AS антижир чистящее средство 500мл',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 13500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧽',
    img: 'photos/asantijir.jpg',
    desc_uz: 'AS Anti-Jir – oshxona yuzalaridagi qattiq yog‘ va kuygan dog‘larni samarali tozalaydi. 500 ml hajmda. Tez va oson ishlatiladi, suvda yaxshi chayiladi. Plita, pech, lavabo va boshqa sirtlar uchun mos.',
    desc_ru: 'AS Антижир – эффективно удаляет стойкий жир и пригоревшие пятна с кухонных поверхностей. Объём 500 мл. Быстро и легко применяется, хорошо смывается водой. Подходит для плит, духовок, раковин и других поверхностей.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 13,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS chistol (limon) 400g',
    name_ru: 'AS чистол (лимон) 400г',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 5500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍋',
    img: 'photos/aschistol400gr.jpg',
    desc_uz: 'AS tozalash kukuni – limon aromati bilan. Tarkibida soda va faol moddalar mavjud. Kir, dog‘ va gidroloklarni samarali tozalaydi. 400 grammli qulay paket. Oshxona, hammom va boshqa yuzalar uchun mos.',
    desc_ru: 'AS чистящий порошок – с ароматом лимона. Содержит соду и активные вещества. Эффективно очищает грязь, пятна и налёт. Удобная упаковка 400 г. Подходит для кухни, ванной и других поверхностей.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 19,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS oqartiruvchi vosita',
    name_ru: 'AS отбеливатель',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 6400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '✨',
    img: 'photos/asotbelivatel.jpg',
    desc_uz: 'AS oqartiruvchi – oq va rangli kiyimlarni yangilaydi, sarg‘ayganlik va kulranglikni ketkazadi. Tarkibida faol kislorod va oqartiruvchi komponentlar mavjud. Matoga zarar yetkazmaydi, kiyimlarni porloq qiladi. Har xil turdagi matolar uchun mos.',
    desc_ru: 'AS отбеливатель – обновляет белое и цветное бельё, удаляет желтизну и серость. Содержит активный кислород и отбеливающие компоненты. Не повреждает ткань, делает вещи яркими. Подходит для различных типов тканей.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== ЧИСТЯЩИЕ СРЕДСТВА PEGAS ==========
  {
    id: 30,
    brand_uz: 'Pegas',
    brand_ru: 'Pegas',
    name_uz: 'Pegas gilam va yumshoq mebel tozalovchi 1000ml',
    name_ru: 'Pegas средство для чистки ковров и мягкой мебели 1000мл',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 23500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧹',
    img: 'photos/pegasgilammebel.jpg',
    desc_uz: 'Pegas gilam va yumshoq mebel tozalovchi – dog‘lar va iflosliklarni samarali tozalaydi. Antistatik ta’sirga ega, changni tortmaydi. 1000 ml hajmda. Gilam, divan, kreslo va boshqa yumshoq mebellar uchun mos. Yoqimli hid qoldiradi.',
    desc_ru: 'Pegas средство для чистки ковров и мягкой мебели – эффективно удаляет пятна и загрязнения. Обладает антистатическим действием, не притягивает пыль. Объём 1000 мл. Подходит для ковров, диванов, кресел и другой мягкой мебели. Оставляет приятный аромат.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 31,
    brand_uz: 'Pegas',
    brand_ru: 'Pegas',
    name_uz: 'Pegas salon tozalovchi 500ml',
    name_ru: 'Pegas средство для чистки салона 500мл',
   cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 15600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🚗',
    img: 'photos/pegassalon.jpg',
    desc_uz: 'Pegas salon tozalovchi – avtomobil saloni, plastik, charm va mato yuzalarni tozalash uchun. Kir, dog‘ va changni samarali ketkazadi. 500 ml hajmda. Dezinfeksiya qiluvchi ta’sirga ega. Uyda ham ishlatish mumkin.',
    desc_ru: 'Pegas средство для чистки салона – для очистки автомобильного салона, пластиковых, кожаных и тканевых поверхностей. Эффективно удаляет грязь, пятна и пыль. Объём 500 мл. Обладает дезинфицирующим действием. Можно использовать и дома.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 32,
    brand_uz: 'Pegas',
    brand_ru: 'Pegas',
    name_uz: 'Pegas Krot quvur tozalovchi',
    name_ru: 'Pegas Крот средство для прочистки труб',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 18200,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🔧',
    img: 'photos/pegaskrot.jpg',
    desc_uz: 'Pegas Krot – oshxona va hammom quvurlaridagi tiqilib qolishlarni samarali bartaraf qiladi. 20 daqiqa ichida ishlaydi. Yog‘, soch va boshqa organik qoldiqlarni eritadi. Dezinfeksiya qiluvchi ta’sirga ega, hidni yo‘qotadi.',
    desc_ru: 'Pegas Крот – эффективно устраняет засоры в кухонных и ванных трубах. Действует за 20 минут. Растворяет жир, волосы и другие органические отложения. Обладает дезинфицирующим действием, устраняет запахи.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 33,
    brand_uz: 'Pegas',
    brand_ru: 'Pegas',
    name_uz: 'Pegas avtoshampun',
    name_ru: 'Pegas автошампунь',
   cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 22000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🚿',
    img: 'photos/pegas avtoshampun.jpg',
    desc_uz: 'Pegas avtoshampun – avtomobil kuzovini samarali va yumshoq tozalaydi. Kir, chang va yo‘l iflosliklarini ketkazadi. Lakkiritga zarar yetkazmaydi, porloq qiladi. Konsentrlangan formula – oz miqdorda ko‘p ko‘pik hosil qiladi.',
    desc_ru: 'Pegas автошампунь – эффективно и бережно очищает кузов автомобиля. Удаляет грязь, пыль и дорожные загрязнения. Не повреждает лакокрасочное покрытие, придаёт блеск. Концентрированная формула – небольшое количество даёт обильную пену.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== СРЕДСТВА ДЛЯ СТЁКОЛ ==========
  {
    id: 20,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS oyna yuvish vositasi 500ml',
    name_ru: 'AS средство для мытья стёкол 500мл',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 5400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🪟',
    img: 'photos/asoyna500ml.jpg',
    desc_uz: 'AS oyna yuvish vositasi – oyna, kuzgu va shisha yuzalarni tozalash uchun. 500 ml hajmda. Kir va changni tez ketkazadi, chiziq va iz qoldirmaydi. Yangilovchi, toza hid qoldiradi. Uyda va avtomobil oynalarida ishlatish mumkin.',
    desc_ru: 'AS средство для мытья стёкол – для очистки окон, зеркал и стеклянных поверхностей. Объём 500 мл. Быстро удаляет грязь и пыль, не оставляет разводов и следов. Оставляет освежающий, чистый аромат. Можно использовать в доме и для автомобильных стёкол.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 21,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS oyna yuvish vositasi 700ml',
    name_ru: 'AS средство для мытья стёкол 700мл',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 6400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🪟',
    img: 'photos/asoyna700ml.jpg',
    desc_uz: 'AS oyna yuvish vositasi – katta hajm (700 ml) iqtisodiy paket. Oyna, kuzgi va shisha yuzalarni mukammal tozalaydi. Iz va chiziq qoldirmaydi, tez quriydi. Uy va avtomobil oynalarida foydalanish uchun mos.',
    desc_ru: 'AS средство для мытья стёкол – экономичная упаковка 700 мл. Отлично очищает окна, зеркала и стеклянные поверхности. Не оставляет разводов и следов, быстро сохнет. Подходит для дома и автомобильных стёкол.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== ЖИДКОЕ МЫЛО AS 400мл ==========
  {
    id: 22,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS suyuq sovun (atirgul) 400ml',
    name_ru: 'AS жидкое мыло (роза) 400мл',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 5800,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌹',
    img: 'photos/asqolgelatirgul.jpg',
    desc_uz: 'AS suyuq sovun – atirgul aromati bilan. Qo‘llarni yumshoq tozalaydi, terini namlaydi va himoya qiladi. 400 ml hajmda. Yumshoq va yoqimli hid qoldiradi. Kundalik foydalanish uchun ideal. Dermatologik jihatdan tasdiqlangan.',
    desc_ru: 'AS жидкое мыло – с ароматом розы. Мягко очищает руки, увлажняет и защищает кожу. Объём 400 мл. Оставляет нежный и приятный аромат. Идеально для ежедневного использования. Дерматологически проверено.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 23,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS suyuq sovun (limon) 400ml',
    name_ru: 'AS жидкое мыло (лимон) 400мл',
   cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 5800,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍋',
    img: 'photos/asqolgellimon.jpg',
    desc_uz: 'AS suyuq sovun – limon aromati bilan. Qo‘llarni samarali tozalaydi, yog‘ va iflosliklarni ketkazadi. 400 ml hajmda. Tetiklantiruvchi hid qoldiradi. Kundalik ishlatishga mos, terini yumshoq qiladi.',
    desc_ru: 'AS жидкое мыло – с ароматом лимона. Эффективно очищает руки, удаляет жир и загрязнения. Объём 400 мл. Оставляет освежающий аромат. Подходит для ежедневного использования, делает кожу мягкой.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 24,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS suyuq sovun (olma) 400ml',
    name_ru: 'AS жидкое мыло (яблоко) 400мл',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 5800,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍎',
    img: 'photos/asqolgelolma.jpg',
    desc_uz: 'AS suyuq sovun – olma aromati bilan. Qo‘llarni yumshoq tozalaydi, terini namlik bilan taʼminlaydi. 400 ml hajmda. Yoqimli mevali hid qoldiradi. Barcha teri turlari uchun mos, kundalik foydalanishga tavsiya etiladi.',
    desc_ru: 'AS жидкое мыло – с ароматом яблока. Мягко очищает руки, увлажняет кожу. Объём 400 мл. Оставляет приятный фруктовый аромат. Подходит для всех типов кожи, рекомендуется для ежедневного использования.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== ЖИДКОЕ МЫЛО AS 5л ==========
  {
    id: 34,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS suyuq sovun (atirgul) 5l',
    name_ru: 'AS жидкое мыло (роза) 5л',
  cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 37000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌹',
    img: 'photos/asqolgeli5latirgul.jpg',
    desc_uz: 'AS suyuq sovun – atirgul aromati bilan, 5 litrlik katta iqtisodiy paket. Qo‘llarni yumshoq tozalaydi, terini namlaydi. Katta oila, ofis, mehmonxona va umumiy foydalanish uchun ideal. Yoqimli hid uzoq vaqt saqlanadi.',
    desc_ru: 'AS жидкое мыло – с ароматом розы, большая экономичная упаковка 5 л. Мягко очищает руки, увлажняет кожу. Идеально для большой семьи, офиса, гостиницы и общественного пользования. Приятный аромат сохраняется надолго.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 35,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS suyuq sovun (olma) 5l',
    name_ru: 'AS жидкое мыло (яблоко) 5л',
   cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 37000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍎',
    img: 'photos/asqolgel5lolma.jpg',
    desc_uz: 'AS suyuq sovun – olma aromati bilan, 5 litrlik katta hajm. Qo‘llarni yumshoq tozalaydi, terini namlaydi. Iqtisodiy sarf – uzoq vaqt yetadi. Ofis, mehmonxona va katta oila uchun mos.',
    desc_ru: 'AS жидкое мыло – с ароматом яблока, большой объём 5 л. Мягко очищает руки, увлажняет кожу. Экономичный расход – хватает надолго. Подходит для офиса, гостиницы и большой семьи.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 36,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS suyuq sovun (limon) 5l',
    name_ru: 'AS жидкое мыло (лимон) 5л',
    cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 37000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍋',
    img: 'photos/asqolgel5llimon.jpg',
    desc_uz: 'AS suyuq sovun – limon aromati bilan, 5 litrlik katta paket. Qo‘llarni samarali tozalaydi, tetiklantiruvchi hid qoldiradi. Katta hajm – iqtisodiy, uzoq vaqt foydalanish uchun. Ofis va umumiy joylar uchun ideal.',
    desc_ru: 'AS жидкое мыло – с ароматом лимона, большая упаковка 5 л. Эффективно очищает руки, оставляет освежающий аромат. Большой объём – экономично, для длительного использования. Идеально для офиса и общественных мест.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 37,
    brand_uz: 'AS',
    brand_ru: 'AS',
    name_uz: 'AS suyuq sovun (aqua) 5l',
    name_ru: 'AS жидкое мыло (аква) 5л',
   cat_uz: 'yuvish vositalari',
    cat_ru: 'моющие средства',
    price: 37000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '💧',
    img: 'photos/asqolgel5laqua.jpg',
    desc_uz: 'AS suyuq sovun – yangi, toza aqua aromati bilan. 5 litrlik katta iqtisodiy paket. Qo‘llarni yumshoq tozalaydi, terini namlaydi. Kundalik foydalanish uchun ideal, katta oila va ofislar uchun mos.',
    desc_ru: 'AS жидкое мыло – со свежим, чистым ароматом аква. Большая экономичная упаковка 5 л. Мягко очищает руки, увлажняет кожу. Идеально для ежедневного использования, подходит для большой семьи и офисов.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== ЧАЙ PRINCE OF CHESTER (ПАКЕТИРОВАННЫЙ) ==========
  {
    id: 41,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester yashil choy Original 25 paket',
    name_ru: 'Prince of Chester зелёный чай Original 25 пакетиков',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 10000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍃',
    img: 'photos/chester original 25 paket.jpg',
    desc_uz: 'Prince of Chester yashil choy Original – engil va tetiklantiruvchi ichimlik. Yumshoq o‘simlik notalari va engil achchiqlik bilan yangi taʼmga ega. Ertalabki uyg‘onish, kunduzgi tanaffus yoki tinch kechki choy uchun ideal. Har bir paketda 25 ta qulay paketcha mavjud.',
    desc_ru: 'Prince of Chester зелёный чай Original – мягкий и освежающий напиток. Свежий вкус с тонкими растительными нотками и лёгкой естественной горчинкой. Идеален для утреннего пробуждения, дневной паузы или спокойного вечера. В упаковке 25 удобных пакетиков.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 42,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester qora choy Gold 25 paket',
    name_ru: 'Prince of Chester чёрный чай Gold 25 пакетиков',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 10000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🫖',
    img: 'photos/chester gold 25 paket.jpg',
    desc_uz: 'Prince of Chester qora choy Gold – Seylonning eng yaxshi plantatsiyalaridan terilgan yuqori sifatli choy. Boy, to‘yimli taʼm va yoqimli hidga ega. 25 paketli qulay formatda. Ertalabki nonushta, ish uchrashuvlari yoki oilaviy choy uchun ajoyib tanlov.',
    desc_ru: 'Prince of Chester чёрный чай Gold – высококачественный чай с лучших плантаций Цейлона. Богатый, насыщенный вкус и приятный аромат. Удобный формат 25 пакетиков. Отличный выбор для завтрака, деловых встреч или семейного чаепития.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 43,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester qora choy English Breakfast 25 paket',
    name_ru: 'Prince of Chester чёрный чай English Breakfast 25 пакетиков',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 10000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '☕',
    img: 'photos/chester english breakfast 25 paket.jpg',
    desc_uz: 'Prince of Chester qora choy English Breakfast – klassik ingliz nonushta choyi. Boy, to‘yimli taʼm va ajoyib hidga ega. Ertalabki quvvat va energiya uchun ideal. Sut, limon yoki shakar bilan ayniqsa mazali. 25 paketli qulay paket.',
    desc_ru: 'Prince of Chester чёрный чай English Breakfast – классический английский завтрак. Богатый, насыщенный вкус и прекрасный аромат. Идеален для утренней бодрости и энергии. Особенно вкусен с молоком, лимоном или сахаром. Удобная упаковка 25 пакетиков.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 44,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester yashil choy Yasmin 25 paket',
    name_ru: 'Prince of Chester зелёный чай Жасмин 25 пакетиков',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 10000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌸',
    img: 'photos/chester jasmine 25 paket.jpg',
    desc_uz: 'Prince of Chester yashil choy Yasemin – nozik yasemin gullari xushbo‘y hidiga ega ajoyib choy. Yengil va tetiklantiruvchi taʼmga ega. 25 paketli qulay format. Stressni yengillashtiradi va kayfiyatni ko‘taradi. Ertalab va kechki choy uchun ajoyib tanlov.',
    desc_ru: 'Prince of Chester зелёный чай Жасмин – изысканный чай с нежным ароматом цветов жасмина. Обладает лёгким и освежающим вкусом. Удобный формат 25 пакетиков. Снимает стресс и поднимает настроение. Отличный выбор для утреннего и вечернего чаепития.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== ЧАЙ PRINCE OF CHESTER (РАССЫПНОЙ) ==========
  {
    id: 45,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester yashil choy Original 80g',
    name_ru: 'Prince of Chester зелёный чай Original 80г',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 12500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍃',
    img: 'photos/chester original 80gr.jpg',
    desc_uz: 'Prince of Chester yashil choy Original – engil va tetiklantiruvchi ichimlik. Yumshoq o‘simlik notalari va engil achchiqlik bilan yangi taʼmga ega. 80 grammli qulay paketda. Ertalabki uyg‘onish, kunduzgi tanaffus yoki tinch kechki choy uchun ideal.',
    desc_ru: 'Prince of Chester зелёный чай Original – мягкий и освежающий напиток. Свежий вкус с тонкими растительными нотками и лёгкой естественной горчинкой. В удобной упаковке 80 г. Идеален для утреннего пробуждения, дневной паузы или спокойного вечера.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 46,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester qora choy Gold 80g',
    name_ru: 'Prince of Chester чёрный чай Gold 80г',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 12500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🫖',
    img: 'photos/chester gold 80gr.jpg',
    desc_uz: 'Prince of Chester qora choy Gold – Seylonning eng yaxshi plantatsiyalaridan terilgan yuqori sifatli choy. Boy, to‘yimli taʼm va yoqimli hidga ega. 80 grammli paketda. Ertalabki nonushta, ish uchrashuvlari yoki oilaviy choy uchun ajoyib tanlov.',
    desc_ru: 'Prince of Chester чёрный чай Gold – высококачественный чай с лучших плантаций Цейлона. Богатый, насыщенный вкус и приятный аромат. В упаковке 80 г. Отличный выбор для завтрака, деловых встреч или семейного чаепития.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 47,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester qora choy English Breakfast 80g',
    name_ru: 'Prince of Chester чёрный чай English Breakfast 80г',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 12500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '☕',
    img: 'photos/chester english breakfast 80gr.jpg',
    desc_uz: 'Prince of Chester qora choy English Breakfast – klassik ingliz nonushta choyi. Boy, to‘yimli taʼm va ajoyib hidga ega. 80 grammli paketda. Ertalabki quvvat va energiya uchun ideal. Sut, limon yoki shakar bilan ayniqsa mazali.',
    desc_ru: 'Prince of Chester чёрный чай English Breakfast – классический английский завтрак. Богатый, насыщенный вкус и прекрасный аромат. В упаковке 80 г. Идеален для утренней бодрости и энергии. Особенно вкусен с молоком, лимоном или сахаром.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 48,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester qora choy Big Leaf 80g',
    name_ru: 'Prince of Chester чёрный чай Big Leaf 80г',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 13500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍃',
    img: 'photos/chester big leaf 80gr.jpg',
    desc_uz: 'Prince of Chester qora choy Big Leaf – katta bargli Seylon choyi. Yumshoq, to‘yimli taʼm va boy xushbo‘y hidga ega. 80 grammli paketda. Yuqori sifatli choy barglari to‘liq o‘z taʼmini ochib beradi. Haqiqiy choy biluvchilar uchun.',
    desc_ru: 'Prince of Chester чёрный чай Big Leaf – цейлонский чай из крупного листа. Обладает мягким, насыщенным вкусом и богатым ароматом. В упаковке 80 г. Высококачественные чайные листья полностью раскрывают свой вкус. Для настоящих ценителей чая.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 49,
    brand_uz: 'Prince of Chester',
    brand_ru: 'Prince of Chester',
    name_uz: 'Prince of Chester qora choy Earl Grey 80g',
    name_ru: 'Prince of Chester чёрный чай Earl Grey 80г',
    cat_uz: 'choy',
    cat_ru: 'чай',
    price: 12500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍋',
    img: 'photos/chester earl grey 80gr.jpg',
    desc_uz: 'Prince of Chester qora choy Earl Grey – nozik bergamot xushbo‘y hidiga ega klassik ingliz choyi. Yengil sitrus notalari bilan boy, to‘yimli taʼm. 80 grammli paketda. Ertalab va kechki choy uchun ajoyib tanlov. Haqiqiy ingliz anʼanalari.',
    desc_ru: 'Prince of Chester чёрный чай Earl Grey – классический английский чай с тонким ароматом бергамота. Богатый, насыщенный вкус с лёгкими цитрусовыми нотами. В упаковке 80 г. Отличный выбор для утреннего и вечернего чаепития. Истинные английские традиции.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== НАПИТКИ GOAL MOXITO ==========
  {
    id: 50,
    brand_uz: 'Goal Moxito',
    brand_ru: 'Goal Moxito',
    name_uz: 'Goal Moxito qulupnay va laym 500ml',
    name_ru: 'Goal Moxito клубника и лайм 500мл',
    cat_uz: 'ichimliklar',
    cat_ru: 'напитки',
    price: 9600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍓',
    img: 'photos/goal moxito qulupnay.jpg',
    desc_uz: 'Goal Moxito – tetiklantiruvchi gazlangan ichimlik. Qulupnay va laymning ajoyib kombinatsiyasi – shirin va nordon taʼmlar uygʻunligi. 500 ml hajmda. Issiq kunlarda chanqoqni qoldiradi va kayfiyatni koʻtaradi. Tabiiy taʼm va yangi hid.',
    desc_ru: 'Goal Moxito – освежающий газированный напиток. Превосходное сочетание клубники и лайма – гармония сладкого и кислого вкуса. Объём 500 мл. В жаркие дни утоляет жажду и поднимает настроение. Натуральный вкус и свежий аромат.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 51,
    brand_uz: 'Goal Moxito',
    brand_ru: 'Goal Moxito',
    name_uz: 'Goal Moxito laym 500ml',
    name_ru: 'Goal Moxito лайм 500мл',
    cat_uz: 'ichimliklar',
    cat_ru: 'напитки',
    price: 9600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍋',
    img: 'photos/goal moxito lime.jpg',
    desc_uz: 'Goal Moxito – tetiklantiruvchi gazlangan ichimlik. Laymning yangi va nordon taʼmi bilan. 500 ml hajmda. Issiq kunlarda chanqoqni qoldiradi va tetiklashtiradi. Tabiiy laym taʼmi va yoqimli hid.',
    desc_ru: 'Goal Moxito – освежающий газированный напиток. Со свежим и кисловатым вкусом лайма. Объём 500 мл. В жаркие дни утоляет жажду и освежает. Натуральный вкус лайма и приятный аромат.',
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== ОСИЁ ОШХОНАСИ / АЗИАТСКАЯ КУХНЯ ==========

  // ----- Соевые соусы SEN SOY -----
  {
    id: 52,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Classic soya sousi',
    name_ru: 'Sen Soy соус соевый Classic',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 17300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🫙',
    img: 'photos/sensoy classic.jpg',
    desc_uz: "Sen Soy Classic soya sousi tabiiy fermentatsiya usulida tayyorlangan. O'rtacha tuzli va o'rtacha quyuq bo'lib, har qanday taomga mos keladi. Sharq va Osiyo oshxonasining barcha taomlari uchun universal asos.",
    desc_ru: "Классический соевый соус Sen Soy приготовлен методом естественного брожения. В меру соленый и густой, универсален в использовании. Является основой для всех блюд восточной и азиатской кухни.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 53,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy yengil soya sousi',
    name_ru: 'Sen Soy соус соевый легкий',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 17300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🫙',
    img: 'photos/sensoy soya yengil.jpg',
    desc_uz: "Sen Soy yengil soya sousi – tarkibida kamroq tuz va xushbo'y moddalar mavjud. U engil ta'mga ega bo'lib, salatlar, baliq va sabzavotli taomlar uchun ajoyib qo'shimcha hisoblanadi.",
    desc_ru: "Легкий соевый соус Sen Soy содержит меньше соли и ароматических веществ. Обладает более нежным вкусом, отлично подходит для салатов, рыбы и овощных блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 54,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy quyuq soya sousi (Dark)',
    name_ru: 'Sen Soy соус соевый темный (Dark)',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 23300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🫙',
    img: 'photos/sensoy qora sous.jpg',
    desc_uz: "Sen Soy quyuq soya sousi yopishqoq konsistensiyaga va karamel notalari bilan yorqin ta'mga ega. Go'sht, baliq, lag'mon va sabzavotli taomlar uchun ideal. Iqtisodiy sarflanadi.",
    desc_ru: "Темный соевый соус Sen Soy имеет тягучую консистенцию и яркий вкус с карамельными нотами. Идеален для мяса, рыбы, лапши и овощных блюд. Экономичен в использовании.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 55,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy sushi va sashimi uchun soya sousi',
    name_ru: 'Sen Soy соус соевый для суши и сашими',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 23300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍣',
    img: 'photos/sensoy sushi,sashimi sous.jpg',
    desc_uz: "Sen Soy sushi va sashimi uchun soya sousi – nozik va muvozanatli ta'mga ega. Tarkibida kamroq tuz bo'lib, dengiz mahsulotlari ta'mini to'ldiradi. Sushi, sashimi va boshqa yapon taomlari uchun maxsus ishlab chiqilgan.",
    desc_ru: "Соевый соус для суши и сашими Sen Soy имеет нежный, сбалансированный вкус и пониженное содержание соли. Подчеркивает вкус морепродуктов. Специально разработан для суши, сашими и других японских блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 56,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Premium soya sousi',
    name_ru: 'Sen Soy Premium соус соевый',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 34100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🫙',
    img: 'photos/sensoy classic soya sous.jpg',
    desc_uz: "Sen Soy Premium soya sousi uzoqroq vaqt yetiltirilgan, bu unga yanada to'yingan ta'm va xushbo'y hid beradi. Yuqori sifatli taomlar va gurme tajribalar uchun ajoyib tanlov.",
    desc_ru: "Премиальный соевый соус Sen Soy выдерживается дольше, что придает ему более насыщенный вкус и аромат. Отличный выбор для блюд высокого качества и гурманских экспериментов.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 57,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy pryaniy soya sousi',
    name_ru: 'Sen Soy пряный соевый соус',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 17300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌶️',
    img: 'photos/sensoy pryaniy.jpg',
    desc_uz: "Sen Soy pryaniy soya sousi – achchiq va xushbo'y qo'shimchalar bilan boyitilgan. Go'sht, lag'mon va qovurilgan taomlarga o'ziga xos ziravorli ta'm beradi.",
    desc_ru: "Пряный соевый соус Sen Soy обогащен острыми и ароматными добавками. Придает мясу, лапше и жареным блюдам пикантный, насыщенный вкус.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 58,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy qizil chili sousi',
    name_ru: 'Sen Soy соус чили жгучий',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 16100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌶️',
    img: 'photos/sensoy achchiq chili.jpg',
    desc_uz: "Sen Soy qizil chili sousi – o'rtacha achchiq, shirin va nordon ta'mga ega. Qovurilgan taomlar, lag'mon va sushi uchun ajoyib sous. Chili va sarimsoqning tabiiy xushbo'yligi.",
    desc_ru: "Соус красный чили Sen Soy имеет средне-острый, сладковато-кислый вкус. Отлично подходит к жареным блюдам, лапше и суши. Натуральный аромат чили и чеснока.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 59,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy shirin chili sousi',
    name_ru: 'Sen Soy сладкий чили соус',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 16100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌶️',
    img: 'photos/sensoy shirin chili.jpg',
    desc_uz: "Sen Soy shirin chili sousi – shirin va o'rtacha achchiq ta'mga ega. Qovurilgan qanotlar, lag'mon, sushi va rolls uchun ideal. Yumshoq chili ta'mi va yoqimli hid.",
    desc_ru: "Сладкий чили соус Sen Soy имеет сладкий и умеренно острый вкус. Идеален к жареным крылышкам, лапше, суши и роллам. Мягкий вкус чили и приятный аромат.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 60,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy shirin chili ananasli',
    name_ru: 'Sen Soy сладкий чили с ананасом',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍍',
    img: 'photos/sensoy shirin chili ananasli.jpg',
    desc_uz: "Sen Soy shirin chili ananasli – tropik meva notalari bilan boyitilgan. Shirin va achchiq uyg'unligi, ananasning tetiklantiruvchi ta'mi. Qovurilgan go'sht, tovuq va dengiz mahsulotlari uchun ajoyib.",
    desc_ru: "Сладкий чили с ананасом Sen Soy обогащен тропическими нотками. Гармония сладкого и острого, освежающий вкус ананаса. Отлично подходит к жареному мясу, курице и морепродуктам.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 61,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy shirin chili mango',
    name_ru: 'Sen Soy сладкий чили с манго',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🥭',
    img: 'photos/sensoy shirin chili mango.jpg',
    desc_uz: "Sen Soy shirin chili mango – mango mevasining shirin va nordon ta'mi bilan boyitilgan. Achchiqlik va mevali tetiklikning ajoyib uyg'unligi. Qovurilgan taomlar va salatlarga mos.",
    desc_ru: "Сладкий чили с манго Sen Soy сочетает сладковато-кислый вкус манго с остринкой чили. Превосходное сочетание для жареных блюд и салатов.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 62,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Spiracha sousi',
    name_ru: 'Sen Soy соус Spiracha',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌶️',
    img: 'photos/sensoy spiracha.jpg',
    desc_uz: "Sen Soy Spiracha – tayland oshxonasining mashhur achchiq sousi. Chili, sarimsoq va sirkadan tayyorlanadi. O'rtacha achchiq va o'ziga xos ta'mga ega. Qovurilgan taomlar, lag'mon va burgerlar uchun ideal.",
    desc_ru: "Соус Spiracha Sen Soy – популярный острый соус тайской кухни. Готовится из чили, чеснока и уксуса. Умеренно острый с характерным вкусом. Идеален к жареным блюдам, лапше и бургерам.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 63,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Teriyaki sousi (klassik)',
    name_ru: 'Sen Soy соус Терияки классический',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍯',
    img: 'photos/sensoy teriyaki sladkiy.jpg',
    desc_uz: "Sen Soy Teriyaki sousi – soya sousi, sake, mirin va shakardan tayyorlangan yapon sousi. Shirin va sho'r ta'm uyg'unligi. Go'sht, baliq va sabzavotlarni qovurish uchun ideal.",
    desc_ru: "Соус Терияки Sen Soy – японский соус на основе соевого соуса, саке, мирина и сахара. Сладковато-соленый вкус. Идеален для обжаривания мяса, рыбы и овощей.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 64,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Teriyaki kunjutli',
    name_ru: 'Sen Soy Терияки с кунжутом',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🥜',
    img: 'photos/sensoy teriyaki kunjutli.jpg',
    desc_uz: "Sen Soy Teriyaki kunjutli – klassik teriyaki sousiga qovurilgan kunjut qo'shilgan. Yog'li va xushbo'y ta'mga ega. Qovurilgan go'sht, baliq va sabzavotlar uchun ajoyib.",
    desc_ru: "Терияки с кунжутом Sen Soy – классический соус терияки с добавлением жареного кунжута. Придает блюдам ореховый, ароматный вкус. Отлично подходит к жареному мясу, рыбе и овощам.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 65,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Unagi sousi (marinad)',
    name_ru: 'Sen Soy соус Унаги (маринад)',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🐟',
    img: 'photos/sensoy unagi sous.jpg',
    desc_uz: "Sen Soy Unagi sousi – yapon oshxonasida ilonbaliq (unagi) uchun ishlatiladigan qalin, shirin-soya sousi. Balık, qovurilgan go'sht va lag'mon uchun ideal marinad va sous.",
    desc_ru: "Соус Унаги Sen Soy – густой сладковато-соевый соус, используемый в японской кухне для угря (унаги). Идеальный маринад и соус для рыбы, жареного мяса и лапши.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 66,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Oyster sousi',
    name_ru: 'Sen Soy соус Устричный',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🦪',
    img: 'photos/sensoy oister sous.jpg',
    desc_uz: "Sen Soy Oyster sousi – ustrilarni qaynatishdan olingan sharbat asosida tayyorlanadi. U o'ziga xos dengiz ta'mi va xushbo'y hidga ega. Qovurilgan go'sht, baliq va sabzavotlar bilan yaxshi uyg'unlashadi.",
    desc_ru: "Устричный соус Sen Soy готовится на основе вываренного сока устриц. Обладает характерным морским вкусом и ароматом. Отлично сочетается с жареным мясом, рыбой и овощами.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 67,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Wok sousi',
    name_ru: 'Sen Soy соус для Wok',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍜',
    img: 'photos/sensoy wok.jpg',
    desc_uz: "Sen Soy Wok sousi – lag'monli taomlar uchun ideal asos. Ushbu sousni lag'monga qo'shish orqali siz qo'shimcha ingredientlarsiz ham tayyor restoran taomini olishingiz mumkin. Go'sht, parranda, lag'mon va sabzavotlarni vok usulida tayyorlash uchun.",
    desc_ru: "Соус для Wok Sen Soy – идеальная основа для блюд из лапши. Добавляя его в лапшу, вы получаете блюдо ресторанного уровня без лишних ингредиентов. Подходит для приготовления мяса, птицы, лапши и овощей в воке.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 68,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy kislo-sladkiy sous',
    name_ru: 'Sen Soy кисло-сладкий соус',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 16100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍍',
    img: 'photos/sensoy sous kislo sladkiy.jpg',
    desc_uz: "Sen Soy kislo-sladkiy sous – an'anaviy xitoy sousi. Shirin va nordon ta'm uyg'unligi, mevali notalar bilan. Qovurilgan go'sht, tovuq, baliq va sabzavotlar uchun ajoyib.",
    desc_ru: "Кисло-сладкий соус Sen Soy – традиционный китайский соус. Гармоничное сочетание сладкого и кислого вкуса с фруктовыми нотами. Отлично подходит к жареному мясу, курице, рыбе и овощам.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Пасты и основы -----
  {
    id: 69,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Tom Yum pastasi',
    name_ru: 'Sen Soy паста Том Ям',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 16100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍲',
    img: 'photos/sensoy osnova dlya supa tom yum.jpg',
    desc_uz: "Sen Soy Tom Yum pastasi – tayland oshxonasining mashhur sho'rva uchun asos. Tarkibida chili, limon grass, galangal, kaffir laym va boshqa ziravorlar. 4 porsiyaga yetarli, konservantlarsiz.",
    desc_ru: "Паста Том Ям Sen Soy – основа для знаменитого тайского супа. Содержит чили, лимонник, галангал, каффир-лайм и другие специи. Достаточно для 4 порций, без консервантов.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Лапша и вермишель -----
  {
    id: 70,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy bug\'doy lag\'moni Somen',
    name_ru: 'Sen Soy пшеничная лапша Сомен',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 29400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍜',
    img: 'photos/sensoy makaron bug\'doy.jpg',
    desc_uz: "Sen Soy bug'doy lag'moni Somen – yupqa va engil bug'doy lag'moni. Tez tayyorlanadi, salatlar, sho'rvalar va qovurilgan taomlar uchun ideal.",
    desc_ru: "Пшеничная лапша Сомен Sen Soy – тонкая и легкая пшеничная лапша. Быстро готовится, идеальна для салатов, супов и жареных блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 71,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy guruchli vermishel',
    name_ru: 'Sen Soy рисовая вермишель',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 29400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍜',
    img: 'photos/lapsha guruchli vermishel.jpg',
    desc_uz: "Sen Soy guruchli vermishel – Osiyo oshxonasining klassik mahsuloti. Guruch unidan tayyorlangan, yengil va mayin. Sho'rvalar, salatlar va qovurilgan taomlar uchun ajoyib.",
    desc_ru: "Рисовая вермишель Sen Soy – классический продукт азиатской кухни. Изготовлена из рисовой муки, легкая и нежная. Отлично подходит для супов, салатов и жареных блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 72,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy guruchli lag\'mon Pho',
    name_ru: 'Sen Soy рисовая лапша Фо',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 29400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍜',
    img: 'photos/guruchli lapsha fo-kho.jpg',
    desc_uz: "Sen Soy guruchli lag'mon Pho – vyetnam oshxonasining mashhur sho'rvasi uchun asos. Yassi va yengil guruch lag'moni. Tez pishadi, sho'rva va qovurilgan taomlarga mos.",
    desc_ru: "Рисовая лапша Фо Sen Soy – основа для знаменитого вьетнамского супа. Плоская и легкая рисовая лапша. Быстро варится, подходит для супов и жареных блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 73,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy guruchli lag\'mon tuxumli',
    name_ru: 'Sen Soy рисовая лапша с яйцом',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 29400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍜',
    img: 'photos/lapsha guruchli tuxum.jpg',
    desc_uz: "Sen Soy guruchli lag'mon tuxum qo'shilgan holda tayyorlangan. U yanada to'yimli va elastik. Qovurilgan lag'mon va sho'rvalar uchun ideal.",
    desc_ru: "Рисовая лапша с яйцом Sen Soy обогащена яйцом, что делает ее более сытной и эластичной. Идеальна для жареной лапши и супов.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 74,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy Udon lag\'moni',
    name_ru: 'Sen Soy лапша Удон',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 29400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍜',
    img: 'photos/sensoy lapsha Udon.jpg',
    desc_uz: "Sen Soy Udon lag'moni – qalin bug'doy lag'moni, yapon oshxonasining klassiki. Yumshoq va elastik, sho'rvalar va qovurilgan taomlar uchun ajoyib.",
    desc_ru: "Лапша Удон Sen Soy – толстая пшеничная лапша, классика японской кухни. Мягкая и упругая, отлично подходит для супов и жареных блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Рисовая бумага -----
  {
    id: 76,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy guruchli qog\'oz (katta) 10 list',
    name_ru: 'Sen Soy рисовая бумага (большая) 10 листов',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 25900,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '📄',
    img: 'photos/sensoy guruchli qog\'oz katta.jpg',
    desc_uz: "Sen Soy guruchli qog'oz – yumshoq va elastik, spring-rolls va nem chuchvaralari uchun. 10 ta katta varaq. Namlash va to'ldirish uchun qulay.",
    desc_ru: "Рисовая бумага Sen Soy – мягкая и эластичная, для спринг-роллов и блинчиков нем. 10 больших листов. Удобна для замачивания и начинки.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Морские водоросли нори -----
  {
    id: 77,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy sushi nori 10 list',
    name_ru: 'Sen Soy нори для суши 10 листов',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 41400,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌿',
    img: 'photos/sensoy sushi nori  10.jpg',
    desc_uz: "Sen Soy sushi nori – yuqori sifatli quritilgan dengiz o'tlari. Sushi va rolls tayyorlash uchun ideal. 10 ta standart o'lchamdagi varaq.",
    desc_ru: "Нори для суши Sen Soy – высококачественные сушеные морские водоросли. Идеальны для приготовления суши и роллов. 10 листов стандартного размера.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Чипсы нори (разные вкусы) -----
  {
    id: 78,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy nori chips original',
    name_ru: 'Sen Soy чипсы нори оригинальные',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 13600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌿',
    img: 'photos/sensoy sushi nori chips original.jpg',
    desc_uz: "Sen Soy nori chips – qovurilgan dengiz o'tlari tayyor gazak. Original ta'mi bilan. Yengil va xushbo'y, pivo va gazaklar uchun ajoyib.",
    desc_ru: "Чипсы нори Sen Soy – обжаренные морские водоросли, готовый снек. Оригинальный вкус. Легкие и ароматные, отлично подходят к пиву и закускам.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 79,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy nori chips wasabi',
    name_ru: 'Sen Soy чипсы нори с васаби',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 13600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌿',
    img: 'photos/sensoy sushi nori chips  wasabi.jpg',
    desc_uz: "Sen Soy nori chips wasabi – qovurilgan dengiz o'tlariga yapon xreni (vasabi) qo'shilgan. Achchiq va tetiklantiruvchi ta'm. Gazaklar uchun ajoyib.",
    desc_ru: "Чипсы нори с васаби Sen Soy – обжаренные морские водоросли с добавлением японского хрена (васаби). Острый и освежающий вкус. Отличный снек.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 80,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy nori chips kimchi',
    name_ru: 'Sen Soy чипсы нори с кимчи',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 13600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌿',
    img: 'photos/sensoy sushi nori chips kimchi.jpg',
    desc_uz: "Sen Soy nori chips kimchi – koreys oshxonasining mashhur ta'mi bilan. Achchiq va nordon, o'ziga xos xushbo'y hid. Gazaklar uchun ajoyib.",
    desc_ru: "Чипсы нори с кимчи Sen Soy – со вкусом знаменитого корейского блюда. Остро-кислый, с характерным ароматом. Отличный снек.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 81,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy nori chips teriyaki',
    name_ru: 'Sen Soy чипсы нори терияки',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 13600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌿',
    img: 'photos/sensoy sushi nori chips teriyaki.jpg',
    desc_uz: "Sen Soy nori chips teriyaki – teriyaki sousi ta'mida. Shirin va sho'r, yoqimli xushbo'y hid. Gazak va pivo uchun ajoyib.",
    desc_ru: "Чипсы нори терияки Sen Soy – со вкусом соуса терияки. Сладковато-соленые, с приятным ароматом. Отличный снек к пиву.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 82,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy nori chips tom yam',
    name_ru: 'Sen Soy чипсы нори том ям',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 13600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌿',
    img: 'photos/sensoy sushi nori chips tom yam.jpg',
    desc_uz: "Sen Soy nori chips tom yam – tayland oshxonasining mashhur ta'mida. Achchiq, nordon va xushbo'y. Gazaklar uchun ajoyib.",
    desc_ru: "Чипсы нори том ям Sen Soy – со вкусом знаменитого тайского супа. Острые, кислые и ароматные. Отличный снек.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 83,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy nori chips olivka',
    name_ru: 'Sen Soy чипсы нори с оливками',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 13600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌿',
    img: 'photos/sensoy sushi nori chips olivka.jpg',
    desc_uz: "Sen Soy nori chips olivka – dengiz o'tlari va zaytun ta'mi uyg'unligi. O'ziga xos va mazali gazak.",
    desc_ru: "Чипсы нори с оливками Sen Soy – сочетание морских водорослей и оливкового вкуса. Необычный и вкусный снек.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Рисовый уксус -----
  {
    id: 84,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy guruch sirkasi',
    name_ru: 'Sen Soy рисовый уксус',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 22000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🧂',
    img: 'photos/sensoy guruch sirkasi.jpg',
    desc_uz: "Sen Soy guruch sirkasi – yumshoq va nozik ta'mga ega. Sushi, salatlar va marinadlar uchun ideal. Osiyo oshxonasining muhim ingredienti.",
    desc_ru: "Рисовый уксус Sen Soy – мягкий и нежный на вкус. Идеален для суши, салатов и маринадов. Важный ингредиент азиатской кухни.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Бренд Yamchan (соевые соусы) -----
  {
    id: 85,
    brand_uz: 'Yamchan',
    brand_ru: 'Yamchan',
    name_uz: 'Yamchan klassik soya sousi',
    name_ru: 'Yamchan соус соевый классический',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 10100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🫙',
    img: 'photos/yamchan soya sous klassik.jpg',
    desc_uz: "Yamchan klassik soya sousi – tabiiy fermentatsiya mahsuloti. 100% tabiiy, konservantlarsiz. O'rtacha tuzli, universal taomlar uchun.",
    desc_ru: "Классический соевый соус Yamchan – продукт естественного брожения. 100% натуральный, без консервантов. В меру соленый, универсальный.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 86,
    brand_uz: 'Yamchan',
    brand_ru: 'Yamchan',
    name_uz: 'Yamchan Teriyaki soya sousi',
    name_ru: 'Yamchan соус соевый Терияки',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 10100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍯',
    img: 'photos/yamchan teriyaki soya sous.jpg',
    desc_uz: "Yamchan Teriyaki sousi – shirin va sho'r ta'mga ega. Go'sht, baliq va sabzavotlarni qovurish uchun ideal. 100% tabiiy.",
    desc_ru: "Соус Терияки Yamchan – сладко-соленый вкус. Идеален для обжаривания мяса, рыбы и овощей. 100% натуральный.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Бренд Paprichi (соусы) -----
  {
    id: 87,
    brand_uz: 'Paprichi',
    brand_ru: 'Paprichi',
    name_uz: 'Paprichi barbeque sousi',
    name_ru: 'Paprichi соус барбекю',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 23300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍖',
    img: 'photos/paprichi barbeque.jpg',
    desc_uz: "Paprichi barbeque sousi – amerika oshxonasining klassiki. Dudlangan, shirin va achchiq notalar bilan. Go'sht va qovurilgan taomlar uchun ideal.",
    desc_ru: "Соус барбекю Paprichi – классика американской кухни. С копчеными, сладкими и острыми нотками. Идеален для мяса и жареных блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 88,
    brand_uz: 'Paprichi',
    brand_ru: 'Paprichi',
    name_uz: 'Paprichi shashlik & kebab sousi',
    name_ru: 'Paprichi соус для шашлыка и кебаба',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 23300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍢',
    img: 'photos/paprichi shashlik kebab.jpg',
    desc_uz: "Paprichi shashlik sousi – qovurilgan go'sht uchun maxsus. Achchiq, xushbo'y va to'yingan ta'mga ega. Shashlik, kebab va mangal uchun ajoyib.",
    desc_ru: "Соус для шашлыка и кебаба Paprichi – специально для жареного мяса. Острый, ароматный и насыщенный. Отлично подходит для шашлыка, кебаба и барбекю.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 89,
    brand_uz: 'Paprichi',
    brand_ru: 'Paprichi',
    name_uz: 'Paprichi shirin-achchiq sous',
    name_ru: 'Paprichi сладко-острый соус',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 23300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌶️',
    img: 'photos/paprichi shirin , achchiq.jpg',
    desc_uz: "Paprichi shirin-achchiq sous – shirinlik va achchiqlik uyg'unligi. Qovurilgan tovuq, lag'mon va rolls uchun ajoyib.",
    desc_ru: "Сладко-острый соус Paprichi – гармония сладости и остроты. Отлично подходит к жареной курице, лапше и роллам.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 90,
    brand_uz: 'Paprichi',
    brand_ru: 'Paprichi',
    name_uz: 'Paprichi kislo-sladkiy sous',
    name_ru: 'Paprichi кисло-сладкий соус',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 23300,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍍',
    img: 'photos/paprichi kislo sladkiy sous.jpg',
    desc_uz: "Paprichi kislo-sladkiy sous – xitoy oshxonasining klassiki. Shirin va nordon ta'm, mevali notalar bilan. Qovurilgan go'sht va sabzavotlar uchun.",
    desc_ru: "Кисло-сладкий соус Paprichi – классика китайской кухни. Сладко-кислый вкус с фруктовыми нотами. Для жареного мяса и овощей.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Лапша быстрого приготовления Gaudo -----
  {
    id: 91,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Gaudo Tom Yam lag\'moni (krevetka)',
    name_ru: 'Gaudo лапша Том Ям с креветкой',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 21500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍜',
    img: 'photos/gaudo lapsha tomyam krevetka.jpg',
    desc_uz: "Gaudo Tom Yam lag'moni – tayland oshxonasining mashhur ta'mida. Kremetka ta'mi bilan, tez tayyorlanadigan lag'mon. Achchiq va xushbo'y.",
    desc_ru: "Лапша Том Ям с креветкой Gaudo – со вкусом знаменитого тайского супа. Быстрого приготовления, с ароматом креветки. Острая и ароматная.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ----- Другие товары SEN SOY (добавленные) -----
  {
    id: 92,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy ramen lag\'moni (korean)',
    name_ru: 'Sen Soy лапша рамен (корейская)',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 21500,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🍜',
    img: 'photos/sensoy ramen korean.jpg',
    desc_uz: "Sen Soy ramen lag'moni – koreys oshxonasiga xos, qalin va elastik lag'mon. Sho'rva va qovurilgan taomlar uchun ideal.",
    desc_ru: "Лапша рамен Sen Soy – характерная для корейской кухни, толстая и упругая лапша. Идеальна для супов и жареных блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },

  // ========== ДОПОЛНИТЕЛЬНЫЕ ТОВАРЫ ==========
  {
    id: 98,
    brand_uz: 'Sen Soy',
    brand_ru: 'Sen Soy',
    name_uz: 'Sen Soy shirin chili sousi (bottled)',
    name_ru: 'Sen Soy соус сладкий чили (бутылка)',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 32600,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌶️',
    img: 'photos/sensoy shirin chili sous.jpg',
    desc_uz: "Sen Soy shirin chili sousi – an'anaviy Osiyo sousi, shirin va o'rtacha achchiq. Qovurilgan tovuq, lag'mon, sushi va rolls uchun ajoyib qo'shimcha.",
    desc_ru: "Сладкий чили соус Sen Soy – традиционный азиатский соус, сладкий и умеренно острый. Прекрасное дополнение к жареной курице, лапше, суши и роллам.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 99,
    brand_uz: 'Yamchan',
    brand_ru: 'Yamchan',
    name_uz: 'Yancon Chili sousi (shirin)',
    name_ru: 'Yancon соус Чили сладкий',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 10100,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌶️',
    img: 'photos/yamchan shirin chili.jpg',
    desc_uz: "Yancon Chili sousi – shirin va o'rtacha achchiq sous. Qovurilgan go'sht, lag'mon va taomlar uchun universal.",
    desc_ru: "Соус Yancon Chili – сладкий и умеренно острый соус. Универсальный для жареного мяса, лапши и других блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  },
  {
    id: 100,
    brand_uz: 'Yamchan',
    brand_ru: 'Yamchan',
    name_uz: 'Yuni Basai Chili sousi (koreys)',
    name_ru: 'Yuni Basai соус Чили корейский',
    cat_uz: 'osiyo oshxonasi',
    cat_ru: 'азиатская кухня',
    price: 7000,
    unit_uz: 'dona',
    unit_ru: 'шт',
    emoji: '🌶️',
    img: 'photos/yamchan achchiq chili.jpg',
    desc_uz: "Yuni Basai Chili sousi – koreys uslubidagi chili sousi. Achchiq va o'ziga xos ta'mga ega. Go'sht, lag'mon va koreys taomlari uchun ideal.",
    desc_ru: "Соус Yuni Basai Chili – соус чили в корейском стиле. Острый и с характерным вкусом. Идеален для мяса, лапши и корейских блюд.",
    promo: '',
    promo_desc_uz: '',
    promo_desc_ru: ''
  }
];

/* ══════════════════════════════════════
   REGIONS & AGENTS
══════════════════════════════════════ */
const regions = [
  {
    name_uz: 'Учтепа',
    name_ru: 'Учтепа',
    agent_uz: 'Mashhura',
    agent_ru: 'Машхура',
    phone: '+998 94 081 16 68',
    telegram: '@Tatyanahon'
  },
  
    {
    name_uz: 'Mirzo Ulug`bek',
    name_ru: 'Мирзо Улугбек',
    agent_uz: 'Dilorom',
    agent_ru: 'Дилором',
    phone: '+998 97 900 01 61',
    telegram: '@dilorom_555'
  },
    
       {
    name_uz: 'Shayxantohur',
    name_ru: 'Шайхантохур',
    agent_uz: 'Davron',
    agent_ru: 'Даврон',
    phone: '',
    telegram: '@Davron299918'
  },
         
    {
    name_uz: 'Yunusobod',
    name_ru: 'Юнусобод',
    agent_uz: 'Begzod',
    agent_ru: 'Бегзод',
    phone: '+998888972898',
    telegram: '@Yurist007'
  },
    /*{
    name_uz: '',
    name_ru: '',
    agent_uz: '',
    agent_ru: '',
    phone: '',
    telegram: ''
  },
    {
    name_uz: '',
    name_ru: '',
    agent_uz: '',
    agent_ru: '',
    phone: '',
    telegram: ''
  },
    {
    name_uz: '',
    name_ru: '',
    agent_uz: '',
    agent_ru: '',
    phone: '',
    telegram: ''
  },*/
];
